Repository shriproperty/admin, pull requests merged in 2022-09, with the labels that each got.

#8 feat: :sparkles: Configure ant design and tailwind
  craco.config.js
  package-lock.json
  package.json
  postcss.config.js
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/app.css
  src/app.less
  src/index.css
  src/index.tsx
  src/logo.svg
  src/reportWebVitals.ts
  src/setupTests.ts
  src/styles/variables.less
  tailwind.config.js
  yarn.lock
Labels: :mag: Ready for Review, :sparkles: enhancement

#13 feat: :sparkles: Create `/Contacts` page
  .vscode/anchors.code-snippets
  .vscode/redux.code-snippets
  .vscode/settings.json
  package.json
  src/App.tsx
  src/actions/contacts.action.ts
  src/hooks/useAddDispatch.ts
  src/hooks/useAppSelector.ts
  src/pages/contacts/index.tsx
  src/reducers/contacts.reducer.ts
  src/slices/contacts.slice.ts
  src/store.ts
  src/types/enum.ts
  src/types/interface.ts
  src/types/types.ts
  src/utils/api.util.ts
  yarn.lock
Labels: :mag: Ready for Review, :sparkles: enhancement

#14 perf(API integration): :zap: do not re fetch contacts if they are already fetched
  src/pages/contacts/index.tsx
Labels: :mag: Ready for Review, :zap: performance

#15 feat: :sparkles: view contact modal
  .vscode/settings.json
  src/actions/contacts.action.ts
  src/pages/contacts/index.tsx
  src/pages/contacts/statusTag/index.tsx
  src/pages/contacts/viewContactModal/index.tsx
  src/reducers/contacts.reducer.ts
  src/slices/contacts.slice.ts
  src/types/interface.ts
Labels: :white_check_mark: Approved, :sparkles: enhancement

#16 feat: :sparkles: created 404 page
  package.json
  src/App.tsx
  src/pages/pageNotFound/index.tsx
  yarn.lock
Labels: :white_check_mark: Approved, :sparkles: enhancement

#23 feat(users): :sparkles: get all users for api
  .vscode/settings.json
  src/.eslintrc
  src/App.tsx
  src/actions/contacts.action.ts
  src/actions/users.action.ts
  src/components/nav/index.tsx
  src/hooks/useFormatDate.ts
  src/pages/contacts/index.tsx
  src/pages/contacts/viewContactModal/index.tsx
  src/pages/pageNotFound/index.tsx
  src/pages/users/index.tsx
  src/pages/users/verifiedTag/index.tsx
  src/reducers/users.reducers.ts
  src/slices/users.slice.ts
  src/store.ts
  src/types/interface.ts
Labels: :white_check_mark: Approved, :sparkles: enhancement
